name: build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - stage
          - prod

concurrency: ${{ inputs.environment }}

jobs:
  testing:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} 

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          exit 1
          
  hello:
    name: second
    needs: testing
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} 
      
    steps:
      - name: list dir
        run: ls -alt

  notify:
    needs: [testing, hello]
    if: failure()
    runs-on: ubuntu-latest
      
    steps:
      - name: Send failure notification
        run: |
          if [[ "${{ inputs.environment }}" == "prod" ]]; then
            GOOGLE_URL=${{ secrets.WEBHOOK_URL_PROD }}
          elif [[ "${{ inputs.environment }}" == "stage" ]]; then
            GOOGLE_URL=${{ secrets.WEBHOOK_URL_STAGE }}
          else
            GOOGLE_URL=${{ secrets.WEBHOOK_URL_DEV }}
          fi

          curl -X POST $GOOGLE_URL \
          -H "Content-Type: application/json" \
          -d '{
            "text": "The pipeline failed in `${{ github.workflow }}` on branch `${{ github.ref }}`."
          }'
