name: build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - stage
          - prod

concurrency: ${{ inputs.environment }}

jobs:
  testing:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} 

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          
  hello:
    name: second
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} 
      
    steps:
      - name: list dir
        run: ls -alt
